[all]
fields = ["label", "confidence_score"]

[soc]
endpoint = "/soc/"     # explicit endpoint may not be necessary
fields = ["job_title", "job_description", "level_of_education", "manage_others", "industry_descr"]
